language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
before_script:
  - 'git clone git://github.com/puppetlabs/hiera-puppet.git spec/fixtures/modules/hiera-puppet'
  - 'mkdir /home/vagrant/.puppet'
  - 'cp spec/fixtures/hiera.yaml /home/vagrant/.puppet/hiera.yaml'
after_script:
  - 'rm /home/vagrant/.puppet/hiera.yaml'
  - 'rmdir /home/vagrant/.puppet'
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.6.12
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.9
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.12
